### ISSUE TITLE
output = input

### ISSUE THREAD

**Issue by michieitel** [sevragorgia/CBAS_Symbionts#1]
running:
`Get_Fasta_Reads_Mapping_To_Genome.pl --fasta_file /home/eitel/assemblies/data/cbas/data/cbas_nanopore_all_trimmed_renamed.fasta --mappings cbas_nanopore_all_to_sspongiarium_50.sam -out cbas_nanopore_all_to_sspongiarum_50_mapped_reads_GRAPHMAP.fasta`

ended up outputting all input reads

**Comment by sevragorgia** [comment]
changed the help of the script to give some advice in this case.

in brief, you need to filter the sam file first using grep to produce a "matching only" sam file. In our case is easy because all sequences in the reference begin with the word NODE.

So, grep "NODE" file.sam >filtered.file.sam

should give you a sam file with only those nanopore reads matching a contig. For the time being that should do it, I will change the script to avoid this step.

Sergio
